### ISSUE TITLE
(Question) Should we have withdraws public ?

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/parity-bridge#14]
https://github.com/poanetwork/parity-bridge/blob/master/contracts/bridge.sol#L165

@akolotov should we make it public?

**Comment by akolotov** [comment]
I do not think so. It uses a hash of the massage as a key. So, in order to get value from this map you need to take produce a message which contains recipient, withdraw value and tx id; then you need to get `sha3()` of this message and only after that call `withdraws()` to see if the message is handled properly.
Since most often you will get the message from transaction which invoke `withdraw()`, you will always see if this transaction generated the event `Withdraw` which means that funds reached recipient.

@rstormsf  your opinion?

**Comment by akolotov** [comment]
@rstormsf should we close it?

**Comment by akolotov** [comment]
We will not expose this map.

**Comment by rstormsf** [comment]
got it
