### ISSUE TITLE
(Feature) Implement Daily Token transfer Limits 

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/parity-bridge#6]
According to our initial vision, we need to implement daily limits in case if all node bridges are compromised and it won't trigger a massive attack.

https://medium.com/oracles-network/cross-chain-bridges-paving-the-way-to-internet-of-blockchains-422ac94bc2e5

**Comment by akolotov** [comment]
Agree. But we need to think of the procedure who and how could change this limit. Will it be done single-handedly by the owner (O)? Or some majority of bridge authorities must vote for this and the owner does the final signature (N+O).
Will we support several owners (N+any of O)? Although it relates slightly to https://github.com/poanetwork/parity-bridge/issues/8.

**Comment by rstormsf** [comment]
it will be handled by authorities(not validators)

**Comment by akolotov** [comment]
I could imagine a situation when owners do not track bridges statuses and needs every day. Whereas authorities are responsible for the bridge health and customer service that's why they could discover a need to increase daily token limit sooner than owners. So, we could develop a process how authorities inform owners about network needs.
I tried to explain such approach above: authorities sign their suggestion (e.g. increase the limit), an event raised for this as so owners can do final action after getting this event.

It could be addressed as a separate issue.
