### ISSUE TITLE
(Feature) Make bridge contract upgradable

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/parity-bridge#7]
ZepplinOs and Aragon presented new way to write smart contract so you can separate the storage and implementation.
https://github.com/zeppelinos/labs
I personally like eternal storage with registry of contracts

**Comment by akolotov** [comment]
I would be very accurate with the ability to upgrade smart contracts. Yes, it is great opportunity to provide fixes and extend the functionality of contracts. But from another side, it means that the contract can change behavior and it will not be the same as user agreed initially when started using the contract. Imagine that initially the bridge contract relayed confirmations and after upgrade started taking some fee for this. There is no simple way to inform users about changes so that's why personally I think twice prior to delegate controlling of my money to upgradable contract. 

It is the same as "the Bank has the right to unilaterally change the list of ..." in real life.

**Comment by rstormsf** [comment]
done.
